apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: karumala-fun-tls
spec:
  secretName: karumala-fun
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: karumala.fun
  dnsNames:
    - karumala.fun
    - www.karumala.fun
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - karumala.fun
          - www.karumala.fun
